import 'package:google_generative_ai/google_generative_ai.dart';


/// Function to generate text using the Gemini AI API.
Future<String?> requestGeminiAI(String prompt) async {
  const String textApiKey = 'AIzaSyAHkOSc-nGgibvOMFPuoQ6GpirpohOh0mw';

  // Initialize the Gemini model for text generation
  final model = GenerativeModel(
    model: 'gemini-1.5-flash',
    apiKey: textApiKey,
  );

  try {
    // Generate text content based on the prompt
    final response = await model.generateContent([Content.text(prompt)]);
    print("Generated Text: ${response.text}");
    return response.text;
  } catch (e) {
    print("Error in text generation: $e");
    return "Error: Unable to generate text.";
  }
}

//AIzaSyAICFkD5iE58HUJFa3-6rQqF08aORCyQDc.

void main() async {
  // Example usage of the requestGeminiAI function for text generation
  final textPrompt = "Explain the benefits of AI in healthcare.";
  final generatedText = await requestGeminiAI(textPrompt);
  print("Text Generated by Gemini AI: $generatedText\n");

  // Example usage of the generateImages function for image generation

}