// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEOjnexQF1tMBWHW_SSuxS_slwoImEJHk',
    appId: '1:77667627114:web:c364b8165d6f83570cda13',
    messagingSenderId: '77667627114',
    projectId: 'aiproject-f2860',
    authDomain: 'aiproject-f2860.firebaseapp.com',
    storageBucket: 'aiproject-f2860.firebasestorage.app',
    measurementId: 'G-TDCZX1R38P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCizHeRYBVu0PgutMiPYGmuRnRViUjx6Cc',
    appId: '1:77667627114:android:59a7f1166b36d34e0cda13',
    messagingSenderId: '77667627114',
    projectId: 'aiproject-f2860',
    storageBucket: 'aiproject-f2860.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxE_wBXB3iTPgEwtVXVjyccZIqzO6Nnrw',
    appId: '1:77667627114:ios:03b7a3ecc961b73e0cda13',
    messagingSenderId: '77667627114',
    projectId: 'aiproject-f2860',
    storageBucket: 'aiproject-f2860.firebasestorage.app',
    iosBundleId: 'com.example.aiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEOjnexQF1tMBWHW_SSuxS_slwoImEJHk',
    appId: '1:77667627114:web:9a3467e1165b12d50cda13',
    messagingSenderId: '77667627114',
    projectId: 'aiproject-f2860',
    authDomain: 'aiproject-f2860.firebaseapp.com',
    storageBucket: 'aiproject-f2860.firebasestorage.app',
    measurementId: 'G-W8YGEQFST1',
  );
}
